# Generated by Django 4.1.2 on 2022-10-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_alter_watchlist_target_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='target_price',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
